name: DockerHub Build

on:
  push:
    branches:
      - master

env:
  DOCKER_REPO: bertux/fuse-rpc
  IMAGE_NAME: bertux/fuse-rpc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check available environment variables
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Build docker image and tag
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.PUB_REPO_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUB_REPO_DOCKERHUB_ACCESS_TOKEN }}
          repository: ${{ env.DOCKER_REPO }}
          tags: latest
          # Only push on git main branch
          push: ${{ startsWith(github.ref, 'refs/heads/main') }}
